version: '3.8'

services:
  install:
    image: ghcr.io/astral-sh/uv:python3.9-bookworm-slim
    container_name: python_sdk_install_container
    working_dir: /app
    volumes:
      - .:/app
      - uv-cache:/root/.cache/uv
    command: uv sync

  app:
    image: ghcr.io/astral-sh/uv:python3.9-bookworm-slim
    container_name: python_sdk_app_container
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - install
    command: uv run python ./run_checks.py

  test:
    image: ghcr.io/astral-sh/uv:python3.9-bookworm-slim
    container_name: python_sdk_test_container
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - install
    command: uv run pytest
    env_file:
      - .env

volumes:
  uv-cache:
