# coding: utf-8

"""
    Server API

    Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

    The version of the OpenAPI document: 4
    Contact: support@fingerprint.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "fingerprint-server-sdk"
VERSION = "8.11.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
    "cryptography",
]

setup(
    name=NAME,
    version=VERSION,
    description="Fingerprint (https://fingerprint.com) is a device intelligence platform offering industry-leading accuracy. Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it&#39;s not intended to be used from the client side, whether it&#39;s a browser or a mobile device.",
    author="Fingerprint Support",
    author_email="support@fingerprint.com",
    url="https://github.com/fingerprintjs/python-sdk",
    keywords=["Fingerprint Server API", "browser", "detection", "fingerprint", "identification",
              "fingerprinting", "browser-fingerprinting", "browser-fingerprint", "fraud-detection", "fraud",
              "audio-fingerprinting", "fingerprintjs", "fingerprintjs-pro", "visitor-identifier"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test"]),
    include_package_data=True,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Security',
    ],
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it&#39;s not intended to be used from the client side, whether it&#39;s a browser or a mobile device. 
    """,  # noqa: E501
    package_data={"fingerprint_server_sdk": ["py.typed"]},
)