"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import pathlib
import re

from setuptools import find_packages, setup

NAME = 'fingerprint-server-sdk'
VERSION = '9.2.0'
PYTHON_REQUIRES = '>= 3.9'
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
REQUIRES = [
    'urllib3 >= 2.1.0, < 3.0.0',
    'python-dateutil >= 2.8.2',
    'pydantic >= 2',
    'typing-extensions >= 4.7.1',
    'cryptography',
]

here = pathlib.Path(__file__).parent.resolve()
long_description = (here / 'README.md').read_text(encoding='utf-8')
long_description = re.sub(
    '<source[^>]*>\n', '', long_description.replace('<picture>\n', '').replace('</picture>\n', '')
)
long_description = re.sub(
    r'(?P<prefix>\[[^]]*]\()(?P<postfix>docs/[^)]*\))',
    r'\g<prefix>https://github.com/fingerprintjs/python-sdk/blob/main/\g<postfix>',
    long_description,
)

setup(
    name=NAME,
    version=VERSION,
    description="Fingerprint (https://fingerprint.com) is a device intelligence platform offering industry-leading accuracy. Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.",  # noqa: E501
    long_description=long_description,
    long_description_content_type='text/markdown',
    license='MIT',
    license_files=['LICENSE'],
    author='Fingerprint Support',
    author_email='support@fingerprint.com',
    project_urls={
        'Changelog': 'https://github.com/fingerprintjs/python-sdk/blob/main/CHANGELOG.md',
        'Code': 'https://github.com/fingerprintjs/python-sdk',
        'Issue Tracker': 'https://github.com/fingerprintjs/python-sdk/issues',
    },
    keywords=[
        'Fingerprint Server API',
        'browser',
        'detection',
        'fingerprint',
        'identification',
        'fingerprinting',
        'browser-fingerprinting',
        'browser-fingerprint',
        'fraud-detection',
        'fraud',
        'audio-fingerprinting',
        'fingerprintjs',
        'fingerprintjs-pro',
        'visitor-identifier',
    ],
    install_requires=REQUIRES,
    packages=find_packages(exclude=['test']),
    include_package_data=True,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Security',
    ],
    package_data={'fingerprint_server_sdk': ['py.typed']},
)
