# coding: utf-8

"""
    Server API

    Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

    The version of the OpenAPI document: 4
    Contact: support@fingerprint.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BotInfo(BaseModel):
    """
    Extended bot information.
    """ # noqa: E501
    category: StrictStr = Field(description="The type and purpose of the bot.")
    provider: StrictStr = Field(description="The organization or company operating the bot.")
    provider_url: Optional[StrictStr] = Field(default=None, description="The URL of the bot provider's website.")
    name: StrictStr = Field(description="The specific name or identifier of the bot.")
    identity: StrictStr = Field(description="The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider’s customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity. ")
    confidence: StrictStr = Field(description="Confidence level of the bot identification.")
    __properties: ClassVar[List[str]] = ["category", "provider", "provider_url", "name", "identity", "confidence"]

    @field_validator('identity')
    def identity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['verified', 'signed', 'spoofed', 'unknown']):
            raise ValueError("must be one of enum values ('verified', 'signed', 'spoofed', 'unknown')")
        return value

    @field_validator('confidence')
    def confidence_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['low', 'medium', 'high']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BotInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BotInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": obj.get("category"),
            "provider": obj.get("provider"),
            "provider_url": obj.get("provider_url"),
            "name": obj.get("name"),
            "identity": obj.get("identity"),
            "confidence": obj.get("confidence")
        })
        return _obj


