"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self

from fingerprint_server_sdk.models.rule_action_header_field import RuleActionHeaderField
from fingerprint_server_sdk.models.rule_action_type import RuleActionType


class EventRuleActionBlock(BaseModel):
    """
    Informs the client the request should be blocked using the response described by this rule action.
    """  # noqa: E501

    type: RuleActionType  # noqa: E501
    status_code: Optional[StrictInt] = Field(default=None, description='A valid HTTP status code.')  # noqa: E501
    headers: Optional[list[RuleActionHeaderField]] = Field(
        default=None, description='A list of headers to send.'
    )  # noqa: E501
    body: Optional[StrictStr] = Field(
        default=None, description='The response body to send to the client.'
    )  # noqa: E501
    __properties: ClassVar[list[str]] = ['type', 'status_code', 'headers', 'body']

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventRuleActionBlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in headers (list)
        _items = []
        if self.headers:
            for _item_headers in self.headers:
                if _item_headers:
                    _items.append(_item_headers.to_dict())
            _dict['headers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventRuleActionBlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'type': obj.get('type'),
                'status_code': obj.get('status_code'),
                'headers': [RuleActionHeaderField.from_dict(_item) for _item in obj['headers']]
                if obj.get('headers') is not None
                else None,
                'body': obj.get('body'),
            }
        )
        return _obj
