"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from fingerprint_server_sdk.models.bot_info import BotInfo
from fingerprint_server_sdk.models.bot_result import BotResult
from fingerprint_server_sdk.models.browser_details import BrowserDetails
from fingerprint_server_sdk.models.event_rule_action import EventRuleAction
from fingerprint_server_sdk.models.identification import Identification
from fingerprint_server_sdk.models.ip_block_list import IPBlockList
from fingerprint_server_sdk.models.ip_info import IPInfo
from fingerprint_server_sdk.models.proximity import Proximity
from fingerprint_server_sdk.models.proxy_confidence import ProxyConfidence
from fingerprint_server_sdk.models.proxy_details import ProxyDetails
from fingerprint_server_sdk.models.raw_device_attributes import RawDeviceAttributes
from fingerprint_server_sdk.models.sdk import SDK
from fingerprint_server_sdk.models.supplementary_id_high_recall import SupplementaryIDHighRecall
from fingerprint_server_sdk.models.tampering_details import TamperingDetails
from fingerprint_server_sdk.models.velocity import Velocity
from fingerprint_server_sdk.models.vpn_confidence import VpnConfidence
from fingerprint_server_sdk.models.vpn_methods import VpnMethods


class Event(BaseModel):
    """
    Contains results from Fingerprint Identification and all active Smart Signals.
    """

    event_id: StrictStr = Field(
        description="Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp For example: `1758130560902.8tRtrH` "
    )
    timestamp: StrictInt = Field(
        description='Timestamp of the event with millisecond precision in Unix time.'
    )
    linked_id: Optional[StrictStr] = Field(
        default=None, description='A customer-provided id that was sent with the request.'
    )
    environment_id: Optional[StrictStr] = Field(
        default=None,
        description='Environment Id of the event. For example: `ae_47abaca3db2c7c43` ',
    )
    suspect: Optional[StrictBool] = Field(
        default=None,
        description='Field is `true` if you have previously set the `suspect` flag for this event using the [Server API Update event endpoint](https://dev.fingerprint.com/reference/updateevent).',
    )
    sdk: Optional[SDK] = None
    replayed: Optional[StrictBool] = Field(
        default=None,
        description='`true` if we determined that this payload was replayed, `false` otherwise. ',
    )
    identification: Optional[Identification] = None
    supplementary_id_high_recall: Optional[SupplementaryIDHighRecall] = None
    tags: Optional[dict[str, Any]] = Field(
        default=None,
        description='A customer-provided value or an object that was sent with the identification request or updated later.',
    )
    url: Optional[StrictStr] = Field(
        default=None,
        description='Page URL from which the request was sent. For example `https://example.com/` ',
    )
    bundle_id: Optional[StrictStr] = Field(
        default=None,
        description='Bundle Id of the iOS application integrated with the Fingerprint SDK for the event. For example: `com.foo.app` ',
    )
    package_name: Optional[StrictStr] = Field(
        default=None,
        description='Package name of the Android application integrated with the Fingerprint SDK for the event. For example: `com.foo.app` ',
    )
    ip_address: Optional[StrictStr] = Field(
        default=None, description='IP address of the requesting browser or bot.'
    )
    user_agent: Optional[StrictStr] = Field(
        default=None,
        description='User Agent of the client, for example: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) ....` ',
    )
    client_referrer: Optional[StrictStr] = Field(
        default=None,
        description='Client Referrer field corresponds to the `document.referrer` field gathered during an identification request. The value is an empty string if the user navigated to the page directly (not through a link, but, for example, by using a bookmark) For example: `https://example.com/blog/my-article` ',
    )
    browser_details: Optional[BrowserDetails] = None
    proximity: Optional[Proximity] = None
    bot: Optional[BotResult] = None
    bot_type: Optional[StrictStr] = Field(
        default=None, description='Additional classification of the bot type if detected. '
    )
    bot_info: Optional[BotInfo] = None
    cloned_app: Optional[StrictBool] = Field(
        default=None,
        description='Android specific cloned application detection. There are 2 values:  * `true` - Presence of app cloners work detected (e.g. fully cloned application found or launch of it inside of a not main working profile detected). * `false` - No signs of cloned application detected or the client is not Android. ',
    )
    developer_tools: Optional[StrictBool] = Field(
        default=None,
        description='`true` if the browser is Chrome with DevTools open or Firefox with Developer Tools open, `false` otherwise. ',
    )
    emulator: Optional[StrictBool] = Field(
        default=None,
        description='Android specific emulator detection. There are 2 values:  * `true` - Emulated environment detected (e.g. launch inside of AVD).  * `false` - No signs of emulated environment detected or the client is not Android. ',
    )
    factory_reset_timestamp: Optional[StrictInt] = Field(
        default=None,
        description='The time of the most recent factory reset that happened on the **mobile device** is expressed as Unix epoch time. When a factory reset cannot be detected on the mobile device or when the request is initiated from a browser,  this field will correspond to the *epoch* time (i.e 1 Jan 1970 UTC) as a value of 0. See [Factory Reset Detection](https://dev.fingerprint.com/docs/smart-signals-overview#factory-reset-detection) to learn more about this Smart Signal. ',
    )
    frida: Optional[StrictBool] = Field(
        default=None,
        description='[Frida](https://frida.re/docs/) detection for Android and iOS devices. There are 2 values: * `true` - Frida detected * `false` - No signs of Frida or the client is not a mobile device. ',
    )
    ip_blocklist: Optional[IPBlockList] = None
    ip_info: Optional[IPInfo] = None
    proxy: Optional[StrictBool] = Field(
        default=None,
        description='IP address was used by a public proxy provider or belonged to a known recent residential proxy ',
    )
    proxy_confidence: Optional[ProxyConfidence] = None
    proxy_details: Optional[ProxyDetails] = None
    incognito: Optional[StrictBool] = Field(
        default=None,
        description='`true` if we detected incognito mode used in the browser, `false` otherwise. ',
    )
    jailbroken: Optional[StrictBool] = Field(
        default=None,
        description='iOS specific jailbreak detection. There are 2 values:  * `true` - Jailbreak detected. * `false` - No signs of jailbreak or the client is not iOS. ',
    )
    location_spoofing: Optional[StrictBool] = Field(
        default=None,
        description='Flag indicating whether the request came from a mobile device with location spoofing enabled.',
    )
    mitm_attack: Optional[StrictBool] = Field(
        default=None,
        description="* `true` - When requests made from your users' mobile devices to Fingerprint servers have been intercepted and potentially modified.  * `false` - Otherwise or when the request originated from a browser. See [MitM Attack Detection](https://dev.fingerprint.com/docs/smart-signals-reference#mitm-attack-detection) to learn more about this Smart Signal. ",
    )
    privacy_settings: Optional[StrictBool] = Field(
        default=None,
        description='`true` if the request is from a privacy aware browser (e.g. Tor) or from a browser in which fingerprinting is blocked. Otherwise `false`. ',
    )
    root_apps: Optional[StrictBool] = Field(
        default=None,
        description="Android specific root management apps detection. There are 2 values:  * `true` - Root Management Apps detected (e.g. Magisk). * `false` - No Root Management Apps detected or the client isn't Android. ",
    )
    rule_action: Optional[EventRuleAction] = None
    suspect_score: Optional[StrictInt] = Field(
        default=None,
        description='Suspect Score is an easy way to integrate Smart Signals into your fraud protection work flow.  It is a weighted representation of all Smart Signals present in the payload that helps identify suspicious activity. The value range is [0; S] where S is sum of all Smart Signals weights.  See more details here: https://dev.fingerprint.com/docs/suspect-score ',
    )
    tampering: Optional[StrictBool] = Field(
        default=None,
        description='Flag indicating browser tampering was detected. This happens when either:   * There are inconsistencies in the browser configuration that cross internal tampering thresholds (see `tampering_details.anomaly_score`).   * The browser signature resembles an "anti-detect" browser specifically designed to evade fingerprinting (see `tampering_details.anti_detect_browser`). ',
    )
    tampering_details: Optional[TamperingDetails] = None
    velocity: Optional[Velocity] = None
    virtual_machine: Optional[StrictBool] = Field(
        default=None,
        description='`true` if the request came from a browser running inside a virtual machine (e.g. VMWare), `false` otherwise. ',
    )
    vpn: Optional[StrictBool] = Field(
        default=None,
        description='VPN or other anonymizing service has been used when sending the request. ',
    )
    vpn_confidence: Optional[VpnConfidence] = None
    vpn_origin_timezone: Optional[StrictStr] = Field(
        default=None, description='Local timezone which is used in timezone_mismatch method. '
    )
    vpn_origin_country: Optional[StrictStr] = Field(
        default=None,
        description='Country of the request (only for Android SDK version >= 2.4.0, ISO 3166 format or unknown). ',
    )
    vpn_methods: Optional[VpnMethods] = None
    high_activity_device: Optional[StrictBool] = Field(
        default=None,
        description='Flag indicating if the request came from a high-activity visitor.',
    )
    raw_device_attributes: Optional[RawDeviceAttributes] = None
    __properties: ClassVar[list[str]] = [
        'event_id',
        'timestamp',
        'linked_id',
        'environment_id',
        'suspect',
        'sdk',
        'replayed',
        'identification',
        'supplementary_id_high_recall',
        'tags',
        'url',
        'bundle_id',
        'package_name',
        'ip_address',
        'user_agent',
        'client_referrer',
        'browser_details',
        'proximity',
        'bot',
        'bot_type',
        'bot_info',
        'cloned_app',
        'developer_tools',
        'emulator',
        'factory_reset_timestamp',
        'frida',
        'ip_blocklist',
        'ip_info',
        'proxy',
        'proxy_confidence',
        'proxy_details',
        'incognito',
        'jailbroken',
        'location_spoofing',
        'mitm_attack',
        'privacy_settings',
        'root_apps',
        'rule_action',
        'suspect_score',
        'tampering',
        'tampering_details',
        'velocity',
        'virtual_machine',
        'vpn',
        'vpn_confidence',
        'vpn_origin_timezone',
        'vpn_origin_country',
        'vpn_methods',
        'high_activity_device',
        'raw_device_attributes',
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sdk
        if self.sdk:
            _dict['sdk'] = self.sdk.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identification
        if self.identification:
            _dict['identification'] = self.identification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of supplementary_id_high_recall
        if self.supplementary_id_high_recall:
            _dict['supplementary_id_high_recall'] = self.supplementary_id_high_recall.to_dict()
        # override the default output from pydantic by calling `to_dict()` of browser_details
        if self.browser_details:
            _dict['browser_details'] = self.browser_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proximity
        if self.proximity:
            _dict['proximity'] = self.proximity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bot_info
        if self.bot_info:
            _dict['bot_info'] = self.bot_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip_blocklist
        if self.ip_blocklist:
            _dict['ip_blocklist'] = self.ip_blocklist.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ip_info
        if self.ip_info:
            _dict['ip_info'] = self.ip_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proxy_details
        if self.proxy_details:
            _dict['proxy_details'] = self.proxy_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rule_action
        if self.rule_action:
            _dict['rule_action'] = self.rule_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tampering_details
        if self.tampering_details:
            _dict['tampering_details'] = self.tampering_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of velocity
        if self.velocity:
            _dict['velocity'] = self.velocity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vpn_methods
        if self.vpn_methods:
            _dict['vpn_methods'] = self.vpn_methods.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw_device_attributes
        if self.raw_device_attributes:
            _dict['raw_device_attributes'] = self.raw_device_attributes.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'event_id': obj.get('event_id'),
                'timestamp': obj.get('timestamp'),
                'linked_id': obj.get('linked_id'),
                'environment_id': obj.get('environment_id'),
                'suspect': obj.get('suspect'),
                'sdk': SDK.from_dict(obj['sdk']) if obj.get('sdk') is not None else None,
                'replayed': obj.get('replayed'),
                'identification': Identification.from_dict(obj['identification'])
                if obj.get('identification') is not None
                else None,
                'supplementary_id_high_recall': SupplementaryIDHighRecall.from_dict(
                    obj['supplementary_id_high_recall']
                )
                if obj.get('supplementary_id_high_recall') is not None
                else None,
                'tags': obj.get('tags'),
                'url': obj.get('url'),
                'bundle_id': obj.get('bundle_id'),
                'package_name': obj.get('package_name'),
                'ip_address': obj.get('ip_address'),
                'user_agent': obj.get('user_agent'),
                'client_referrer': obj.get('client_referrer'),
                'browser_details': BrowserDetails.from_dict(obj['browser_details'])
                if obj.get('browser_details') is not None
                else None,
                'proximity': Proximity.from_dict(obj['proximity'])
                if obj.get('proximity') is not None
                else None,
                'bot': obj.get('bot'),
                'bot_type': obj.get('bot_type'),
                'bot_info': BotInfo.from_dict(obj['bot_info'])
                if obj.get('bot_info') is not None
                else None,
                'cloned_app': obj.get('cloned_app'),
                'developer_tools': obj.get('developer_tools'),
                'emulator': obj.get('emulator'),
                'factory_reset_timestamp': obj.get('factory_reset_timestamp'),
                'frida': obj.get('frida'),
                'ip_blocklist': IPBlockList.from_dict(obj['ip_blocklist'])
                if obj.get('ip_blocklist') is not None
                else None,
                'ip_info': IPInfo.from_dict(obj['ip_info'])
                if obj.get('ip_info') is not None
                else None,
                'proxy': obj.get('proxy'),
                'proxy_confidence': obj.get('proxy_confidence'),
                'proxy_details': ProxyDetails.from_dict(obj['proxy_details'])
                if obj.get('proxy_details') is not None
                else None,
                'incognito': obj.get('incognito'),
                'jailbroken': obj.get('jailbroken'),
                'location_spoofing': obj.get('location_spoofing'),
                'mitm_attack': obj.get('mitm_attack'),
                'privacy_settings': obj.get('privacy_settings'),
                'root_apps': obj.get('root_apps'),
                'rule_action': EventRuleAction.from_dict(obj['rule_action'])
                if obj.get('rule_action') is not None
                else None,
                'suspect_score': obj.get('suspect_score'),
                'tampering': obj.get('tampering'),
                'tampering_details': TamperingDetails.from_dict(obj['tampering_details'])
                if obj.get('tampering_details') is not None
                else None,
                'velocity': Velocity.from_dict(obj['velocity'])
                if obj.get('velocity') is not None
                else None,
                'virtual_machine': obj.get('virtual_machine'),
                'vpn': obj.get('vpn'),
                'vpn_confidence': obj.get('vpn_confidence'),
                'vpn_origin_timezone': obj.get('vpn_origin_timezone'),
                'vpn_origin_country': obj.get('vpn_origin_country'),
                'vpn_methods': VpnMethods.from_dict(obj['vpn_methods'])
                if obj.get('vpn_methods') is not None
                else None,
                'high_activity_device': obj.get('high_activity_device'),
                'raw_device_attributes': RawDeviceAttributes.from_dict(
                    obj['raw_device_attributes']
                )
                if obj.get('raw_device_attributes') is not None
                else None,
            }
        )
        return _obj
