"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class SearchEventsRareDevicePercentileBucket(str, Enum):
    """
    Filter events by Device Rarity percentile bucket. `<p95` - device configuration is in the bottom 95% (most common). `p95-p99` - device is in the 95th to 99th percentile. `p99-p99.5` - device is in the 99th to 99.5th percentile. `p99.5-p99.9` - device is in the 99.5th to 99.9th percentile. `p99.9+` - device is in the top 0.1% (rarest). `not_seen` - device configuration has never been observed before.
    """

    """
    allowed enum values
    """
    LESS_THAN_P95 = '<p95'
    P95_MINUS_P99 = 'p95-p99'
    P99_MINUS_P99_DOT_5 = 'p99-p99.5'
    P99_DOT_5_MINUS_P99_DOT_9 = 'p99.5-p99.9'
    P99_DOT_9_PLUS = 'p99.9+'
    NOT_SEEN = 'not_seen'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SearchEventsRareDevicePercentileBucket from a JSON string"""
        return cls(json.loads(json_str))
