# coding: utf-8

"""
    Server API

    Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 

    The version of the OpenAPI document: 4
    Contact: support@fingerprint.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SearchEventsSdkPlatform(str, Enum):
    """
    Filter events by the SDK Platform associated with the identification event (`sdk.platform` property) . `js` - Javascript agent (Web). `ios` - Apple iOS based devices. `android` - Android based devices. 
    """

    """
    allowed enum values
    """
    JS = 'js'
    ANDROID = 'android'
    IOS = 'ios'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SearchEventsSdkPlatform from a JSON string"""
        return cls(json.loads(json_str))


