"""
Server API
Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.

The version of the OpenAPI document: 4
Contact: support@fingerprint.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing_extensions import Self


class VpnMethods(BaseModel):
    """
    VpnMethods
    """  # noqa: E501

    timezone_mismatch: Optional[StrictBool] = Field(
        default=None,
        description="The browser timezone doesn't match the timezone inferred from the request IP address.",
    )  # noqa: E501
    public_vpn: Optional[StrictBool] = Field(
        default=None,
        description='Request IP address is owned and used by a public VPN service provider.',
    )  # noqa: E501
    auxiliary_mobile: Optional[StrictBool] = Field(
        default=None,
        description='This method applies to mobile devices only. Indicates the result of additional methods used to detect a VPN in mobile devices.',
    )  # noqa: E501
    os_mismatch: Optional[StrictBool] = Field(
        default=None,
        description='The browser runs on a different operating system than the operating system inferred from the request network signature.',
    )  # noqa: E501
    relay: Optional[StrictBool] = Field(
        default=None,
        description="Request IP address belongs to a relay service provider, indicating the use of relay services like [Apple Private relay](https://support.apple.com/en-us/102602) or [Cloudflare Warp](https://developers.cloudflare.com/warp-client/).  * Like VPNs, relay services anonymize the visitor's true IP address. * Unlike traditional VPNs, relay services don't let visitors spoof their location by choosing an exit node in a different country.  This field allows you to differentiate VPN users and relay service users in your fraud prevention logic. ",
    )  # noqa: E501
    __properties: ClassVar[list[str]] = [
        'timezone_mismatch',
        'public_vpn',
        'auxiliary_mobile',
        'os_mismatch',
        'relay',
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VpnMethods from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VpnMethods from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'timezone_mismatch': obj.get('timezone_mismatch'),
                'public_vpn': obj.get('public_vpn'),
                'auxiliary_mobile': obj.get('auxiliary_mobile'),
                'os_mismatch': obj.get('os_mismatch'),
                'relay': obj.get('relay'),
            }
        )
        return _obj
