name: lint

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.11"
      - name: "Install dependencies"
        run: uv sync

      - name: "Run Ruff format check"
        run: "uv run ruff format --check ."

      - name: "Run Ruff linter"
        run: "uv run ruff check ."

      - name: "Run MyPy type checker"
        run: "uv run mypy fingerprint_server_sdk"
